name: Build and Test Docker Container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t simple-flask-app .

      - name: Run Docker container
        run: docker run -d -p 5000:5000 --name flask-app simple-flask-app

      - name: Wait for app to be ready
        run: |
          for i in $(seq 1 30); do
            if curl --silent --fail http://localhost:5000; then
              echo "App is ready after $i attempts."
              # This exit is now correctly indented and will stop the job
              # from proceeding if the test passes.
              exit 0
            fi
            echo "Waiting for app to be ready... (attempt $i/30)"
            sleep 2
          done
          echo "App failed to start within 60 seconds."
          exit 1

      - name: Test application
        # This step is now optional because the previous step ensures the app is running.
        # It is just to ensure the message is what we expect.
        run: |
          max_retries=10
          retry_count=0
          until curl --fail http://localhost:5000 | grep "Hello from Sukuna!" || [ $retry_count -eq $max_retries ]
          do
            echo "Attempt $((retry_count+1)): App not ready, waiting..."
            sleep 2
            retry_count=$((retry_count+1))
          done
          if [ $retry_count -eq $max_retries ]
          then
            echo "Test failed after $max_retries attempts."
            exit 1
          else
            echo "Test successful! Found 'Hello from Sukuna!'."
          fi
